/**
 * 宮城県ダムマスタデータ
 * dam_syoryou_url.txt + ichiran.csv から抽出
 */
export const MIYAGI_DAMS = [
    {
        id: 'okura',
        stationNo: '104007011',
        name: '大倉ダム',
        river: '大倉川',
        waterSystem: '名取川',
        manager: '宮城県',
        totalCapacity: 28000,        // 総貯水容量（千m³）
        effectiveCapacity: 25000,    // 有効貯水容量（千m³）
        usableCapacityFlood: 15000,  // 利水容量・洪水期 6-10月（千m³）
        usableCapacityNonFlood: 25000, // 利水容量・非洪水期（千m³）
        lowestWaterLevel: 240.65,    // 最低水位 (EL. m)
        normalHighWaterLevel: 270.6, // 常時満水位 (EL. m)
        lat: 38.3216,
        lng: 140.7058,
        mudamId: 184,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/184',
        damType: 'マルティプルアーチ式コンクリートダム',
        purpose: ['洪水調節', 'かんがい', '水道', '工業用水', '発電'],
    },
    {
        id: 'tarumizu',
        stationNo: '104007012',
        name: '樽水ダム',
        river: '増田川',
        waterSystem: '名取川',
        manager: '仙台市',
        totalCapacity: 4700,
        effectiveCapacity: 4200,
        usableCapacityFlood: 2200,
        usableCapacityNonFlood: null, // 非洪水期データなし→洪水期と同値
        lat: 38.1777,
        lng: 140.8432,
        mudamId: 185,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/185',
        damType: '中央コア型ロックフィルダム',
        purpose: ['洪水調節', '流水機能維持', '水道'],
    },
    {
        id: 'nanakita',
        stationNo: '104007013',
        name: '七北田ダム',
        river: '七北田川',
        waterSystem: '七北田川',
        manager: '宮城県',
        totalCapacity: 9200,
        effectiveCapacity: 8500,
        usableCapacityFlood: 4000,
        usableCapacityNonFlood: 5800,
        lat: 38.3569,
        lng: 140.7383,
        mudamId: 186,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/186',
        damType: '中央コア型ロックフィルダム',
        purpose: ['洪水調節', '流水機能維持', '水道'],
    },
    {
        id: 'minamikawa',
        stationNo: '104007008',
        name: '南川ダム',
        river: '南川',
        waterSystem: '鳴瀬川',
        manager: '宮城県',
        totalCapacity: 10000,
        effectiveCapacity: 9200,
        usableCapacityFlood: 4800,
        usableCapacityNonFlood: 7200,
        lat: 38.4338,
        lng: 140.8202,
        mudamId: 183,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/183',
        damType: '重力式コンクリート',
        purpose: ['洪水調節', '流水機能維持', '水道'],
    },
    {
        id: 'miyatoko',
        stationNo: '104007010',
        name: '宮床ダム',
        river: '宮床川',
        waterSystem: '鳴瀬川',
        manager: '宮城県',
        totalCapacity: 5400,
        effectiveCapacity: 5000,
        usableCapacityFlood: 3000,
        usableCapacityNonFlood: null,
        lat: 38.3872846928316,
        lng: 140.82252354424745,
        mudamId: 189,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/189',
        damType: '重力式コンクリートダム',
        purpose: ['洪水調節', '流水機能維持', '水道'],
    },
    {
        id: 'sounoseki',
        stationNo: '104007014',
        name: '惣の関ダム',
        river: '勿来川',
        waterSystem: '砂押川',
        manager: '宮城県',
        totalCapacity: 1100,
        effectiveCapacity: 990,
        usableCapacityFlood: 460,
        usableCapacityNonFlood: null,
        lat: 38.3432,
        lng: 140.9891,
        mudamId: 190,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/190',
        damType: '重力式コンクリート',
        purpose: ['洪水調節', '流水機能維持', '水道'],
    },
    {
        id: 'urushizawa',
        stationNo: '104007009',
        name: '漆沢ダム',
        river: '鳴瀬川',
        waterSystem: '鳴瀬川',
        manager: '宮城県',
        totalCapacity: 18000,
        effectiveCapacity: 16000,
        usableCapacityFlood: 6500,
        usableCapacityNonFlood: 12100,
        lat: 38.5724,
        lng: 140.6413,
        mudamId: 182,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/form01/182/2023',
        damType: '中央コア型ロックフィルダム',
        purpose: ['洪水調節', '流水機能維持', '水道', '工業用水', '発電'],
    },
    {
        id: 'kejonuma',
        stationNo: '104007003',
        name: '化女沼ダム',
        river: '長者川',
        waterSystem: '北上川',
        manager: '宮城県',
        totalCapacity: 3020,
        effectiveCapacity: 2880,
        usableCapacityFlood: 700,
        usableCapacityNonFlood: null,
        lat: 38.6265,
        lng: 140.9626,
        mudamId: 187,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/187',
        damType: 'ゾーン型フィルダム',
        purpose: ['洪水調節', '流水機能維持'],
    },
    {
        id: 'kamioosawa',
        stationNo: '104007007',
        name: '上大沢ダム',
        river: '上大沢川',
        waterSystem: '北上川',
        manager: '宮城県',
        totalCapacity: 410,
        effectiveCapacity: 340,
        usableCapacityFlood: 77,
        usableCapacityNonFlood: null,
        lat: 38.79800272769859,
        lng: 140.6394633810411,
        mudamId: 191,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/191',
        damType: 'アースフィルダム',
        purpose: ['洪水調節', '流水機能維持', '水道'],
    },
    {
        id: 'futatsuishi',
        stationNo: '104007024',
        name: '二ツ石ダム',
        river: '—',
        waterSystem: '—',
        manager: '宮城県',
        totalCapacity: 10600,
        effectiveCapacity: 9700,
        usableCapacityFlood: 9700,
        usableCapacityNonFlood: null,
        lat: 38.6378,
        lng: 140.6564,
        mudamId: null,
        mudamUrl: null,
        damType: '—',
        purpose: [],
    },
    {
        id: 'iwadosawa',
        stationNo: '104007025',
        name: '岩堂沢ダム',
        river: '—',
        waterSystem: '—',
        manager: '宮城県',
        totalCapacity: 13480,
        effectiveCapacity: 13000,
        usableCapacityFlood: 13000,
        usableCapacityNonFlood: null,
        lat: 38.69660710707188,
        lng: 140.63889071128946,
        mudamId: null,
        mudamUrl: null,
        damType: '—',
        purpose: [],
    },
    {
        id: 'hanayama',
        stationNo: '104007001',
        name: '花山ダム',
        river: '迫川',
        waterSystem: '北上川',
        manager: '宮城県',
        totalCapacity: 36600,
        effectiveCapacity: 32000,
        usableCapacityFlood: 12000,
        usableCapacityNonFlood: 22000,
        lat: 38.78025314605699,
        lng: 140.86899783871195,
        mudamId: 181,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/181',
        damType: '重力式コンクリートダム',
        purpose: ['洪水調節', '流水機能維持', '水道', '工業用水', '発電'],
    },
    {
        id: 'aratozawa',
        stationNo: '104007005',
        name: '荒砥沢ダム',
        river: '二迫川',
        waterSystem: '北上川',
        manager: '宮城県',
        totalCapacity: 13214,
        effectiveCapacity: 12594,
        usableCapacityFlood: 8738,
        usableCapacityNonFlood: 11969,
        lat: 38.88648909064017,
        lng: 140.85738234918492,
        mudamId: 188,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/form01/188/2023',
        damType: '中央コア型ロックフィル',
        purpose: ['洪水調節', '流水機能維持', 'かんがい', '発電'],
    },
    {
        id: 'oda',
        stationNo: '104007004',
        name: '小田ダム',
        river: '長崎川',
        waterSystem: '北上川',
        manager: '宮城県',
        totalCapacity: 9720,
        effectiveCapacity: 9010,
        usableCapacityFlood: 4500,
        usableCapacityNonFlood: 8000,
        lat: 38.7558,
        lng: 140.8420,
        mudamId: 192,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/form01/192/2023',
        damType: '中央コア型ロックフィルダム',
        purpose: ['洪水調節', 'かんがい'],
    },
    {
        id: 'kurikoma',
        stationNo: '104007002',
        name: '栗駒ダム',
        river: '—',
        waterSystem: '—',
        manager: '宮城県',
        totalCapacity: 13715,
        effectiveCapacity: 12758,
        usableCapacityFlood: 3655,
        usableCapacityNonFlood: null,
        lat: 38.90766971050853,
        lng: 140.91873061243592,
        mudamId: null,
        mudamUrl: null,
        damType: '—',
        purpose: [],
    },
    {
        id: 'harakawa',
        stationNo: '104007015',
        name: '払川ダム',
        river: '伊里前川',
        waterSystem: '伊里前川',
        manager: '宮城県',
        totalCapacity: 950,
        effectiveCapacity: 830,
        usableCapacityFlood: 190,
        usableCapacityNonFlood: null,
        lat: 38.7313,
        lng: 141.4680,
        mudamId: 193,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/form01/193/2023',
        damType: '—',
        purpose: ['洪水調節', '流水機能維持', '水道'],
    },
    {
        id: 'naruko',
        stationNo: '104007201',
        name: '鳴子ダム',
        river: '江合川',
        waterSystem: '北上川',
        manager: '国交省(東北地方整備局)',
        totalCapacity: 50000,
        effectiveCapacity: 35000,
        usableCapacityFlood: 16000,
        usableCapacityNonFlood: 33000,
        lowestWaterLevel: 231,       // 最低水位 (EL. m)
        normalHighWaterLevel: 254,   // 常時満水位 (EL. m)
        lat: 38.7543,
        lng: 140.7050,
        mudamId: 20,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/form01/20/2023',
        damType: 'アーチ式コンクリートダム',
        purpose: ['洪水調節', '流水機能維持', '発電'],
    },
    {
        id: 'kamafusa',
        stationNo: '104007202',
        name: '釜房ダム',
        river: '碁石川',
        waterSystem: '名取川',
        manager: '国交省(東北地方整備局)',
        totalCapacity: 45300,
        effectiveCapacity: 39300,
        usableCapacityFlood: 18300,
        usableCapacityNonFlood: 36400,
        lowestWaterLevel: 133,       // 最低水位 (EL. m)
        normalHighWaterLevel: 149.8, // 常時満水位 (EL. m)
        lat: 38.2003,
        lng: 140.6997,
        mudamId: 22,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/form01/22/2023',
        damType: '重力式コンクリート',
        purpose: ['洪水調節', '流水機能維持', '水道', '工業用水', '発電'],
    },
    {
        id: 'shichikashuku',
        stationNo: '104007203',
        name: '七ヶ宿ダム',
        river: '白石川',
        waterSystem: '阿武隈川',
        manager: '国交省(東北地方整備局)',
        totalCapacity: 109000,
        effectiveCapacity: 99500,
        usableCapacityFlood: 64500,
        usableCapacityNonFlood: null,
        lat: 37.9614,
        lng: 140.5139,
        mudamId: 27,
        mudamUrl: 'https://mudam.nilim.go.jp/chronology/summary/27',
        damType: '中央コア型ロックフィルダム',
        purpose: ['洪水調節', '流水機能維持', 'かんがい', '水道'],
    },
];

/**
 * 渇水レベル定義
 */
export const DROUGHT_LEVELS = {
    NORMAL: {
        id: 'normal',
        label: '正常',
        color: '#22c55e',
        minStorageRate: 50,
        description: '通常運用',
        icon: '🟢',
    },
    CAUTION: {
        id: 'caution',
        label: '注意',
        color: '#eab308',
        minStorageRate: 30,
        description: '状況監視',
        icon: '🟡',
    },
    WARNING: {
        id: 'warning',
        label: '警戒',
        color: '#f97316',
        minStorageRate: 10,
        description: '節水呼びかけ',
        icon: '🟠',
    },
    CRITICAL: {
        id: 'critical',
        label: '危険',
        color: '#ef4444',
        minStorageRate: 0,
        description: '取水制限',
        icon: '🔴',
    },
};

/**
 * 地域設定
 */
export const REGION_CONFIG = {
    miyagi: {
        name: '宮城県',
        center: [38.27, 140.87],
        zoom: 9,
        areaCode: '040000', // 気象庁エリアコード
    },
};
